// All 114 surahs with ayah count and sample ayahs
// Ayahs use placeholder translations for the full Quran experience
export const SURAHS = [
  { id: 1, name: 'Al-Fatihah', arabic: 'الفاتحة', meaning: 'The Opener', ayahCount: 7 },
  { id: 2, name: 'Al-Baqarah', arabic: 'البقرة', meaning: 'The Cow', ayahCount: 286 },
  { id: 3, name: "Al-Imran", arabic: 'آل عمران', meaning: 'Family of Imran', ayahCount: 200 },
  { id: 4, name: "An-Nisa", arabic: 'النساء', meaning: 'The Women', ayahCount: 176 },
  { id: 5, name: "Al-Ma'idah", arabic: 'المائدة', meaning: 'The Table Spread', ayahCount: 120 },
  { id: 6, name: "Al-An'am", arabic: 'الأنعام', meaning: 'The Cattle', ayahCount: 165 },
  { id: 7, name: "Al-A'raf", arabic: 'الأعراف', meaning: 'The Heights', ayahCount: 206 },
  { id: 8, name: 'Al-Anfal', arabic: 'الأنفال', meaning: 'The Spoils of War', ayahCount: 75 },
  { id: 9, name: 'At-Tawbah', arabic: 'التوبة', meaning: 'The Repentance', ayahCount: 129 },
  { id: 10, name: 'Yunus', arabic: 'يونس', meaning: 'Jonah', ayahCount: 109 },
  { id: 11, name: 'Hud', arabic: 'هود', meaning: 'Hud', ayahCount: 123 },
  { id: 12, name: 'Yusuf', arabic: 'يوسف', meaning: 'Joseph', ayahCount: 111 },
  { id: 13, name: "Ar-Ra'd", arabic: 'الرعد', meaning: 'Thunder', ayahCount: 43 },
  { id: 14, name: 'Ibrahim', arabic: 'إبراهيم', meaning: 'Abraham', ayahCount: 52 },
  { id: 15, name: 'Al-Hijr', arabic: 'الحجر', meaning: 'The Stoneland', ayahCount: 99 },
  { id: 16, name: 'An-Nahl', arabic: 'النحل', meaning: 'The Bee', ayahCount: 128 },
  { id: 17, name: "Al-Isra'", arabic: 'الإسراء', meaning: 'The Night Journey', ayahCount: 111 },
  { id: 18, name: 'Al-Kahf', arabic: 'الكهف', meaning: 'The Cave', ayahCount: 110 },
  { id: 19, name: 'Maryam', arabic: 'مريم', meaning: 'Mary', ayahCount: 98 },
  { id: 20, name: 'Ta-Ha', arabic: 'طه', meaning: 'Ta-Ha', ayahCount: 135 },
  { id: 21, name: "Al-Anbiya'", arabic: 'الأنبياء', meaning: 'The Prophets', ayahCount: 112 },
  { id: 22, name: 'Al-Hajj', arabic: 'الحج', meaning: 'The Pilgrimage', ayahCount: 78 },
  { id: 23, name: "Al-Mu'minun", arabic: 'المؤمنون', meaning: 'The Believers', ayahCount: 118 },
  { id: 24, name: 'An-Nur', arabic: 'النور', meaning: 'The Light', ayahCount: 64 },
  { id: 25, name: 'Al-Furqan', arabic: 'الفرقان', meaning: 'The Criterion', ayahCount: 77 },
  { id: 26, name: "Ash-Shu'ara'", arabic: 'الشعراء', meaning: 'The Poets', ayahCount: 227 },
  { id: 27, name: 'An-Naml', arabic: 'النمل', meaning: 'The Ants', ayahCount: 93 },
  { id: 28, name: 'Al-Qasas', arabic: 'القصص', meaning: 'The Story', ayahCount: 88 },
  { id: 29, name: "Al-'Ankabut", arabic: 'العنكبوت', meaning: 'The Spider', ayahCount: 69 },
  { id: 30, name: 'Ar-Rum', arabic: 'الروم', meaning: 'The Romans', ayahCount: 60 },
  { id: 31, name: 'Luqman', arabic: 'لقمان', meaning: 'Luqman', ayahCount: 34 },
  { id: 32, name: 'As-Sajdah', arabic: 'السجدة', meaning: 'Prostration', ayahCount: 30 },
  { id: 33, name: 'Al-Ahzab', arabic: 'الأحزاب', meaning: 'The Confederates', ayahCount: 73 },
  { id: 34, name: "Saba'", arabic: 'سبأ', meaning: 'Sheba', ayahCount: 54 },
  { id: 35, name: 'Fatir', arabic: 'فاطر', meaning: 'The Originator', ayahCount: 45 },
  { id: 36, name: 'Ya-Sin', arabic: 'يس', meaning: 'Ya Sin', ayahCount: 83 },
  { id: 37, name: 'As-Saffat', arabic: 'الصافات', meaning: 'Those Who Set the Ranks', ayahCount: 182 },
  { id: 38, name: 'Sad', arabic: 'ص', meaning: 'The Letter Saad', ayahCount: 88 },
  { id: 39, name: 'Az-Zumar', arabic: 'الزمر', meaning: 'The Troops', ayahCount: 75 },
  { id: 40, name: 'Ghafir', arabic: 'غافر', meaning: 'The Forgiver', ayahCount: 85 },
  { id: 41, name: 'Fussilat', arabic: 'فصلت', meaning: 'Explained in Detail', ayahCount: 54 },
  { id: 42, name: 'Ash-Shura', arabic: 'الشورى', meaning: 'The Consultation', ayahCount: 53 },
  { id: 43, name: 'Az-Zukhruf', arabic: 'الزخرف', meaning: 'The Ornaments of Gold', ayahCount: 89 },
  { id: 44, name: 'Ad-Dukhan', arabic: 'الدخان', meaning: 'The Smoke', ayahCount: 59 },
  { id: 45, name: 'Al-Jathiyah', arabic: 'الجاثية', meaning: 'The Crouching', ayahCount: 37 },
  { id: 46, name: 'Al-Ahqaf', arabic: 'الأحقاف', meaning: 'The Wind-Curved Sandhill', ayahCount: 35 },
  { id: 47, name: 'Muhammad', arabic: 'محمد', meaning: 'Muhammad', ayahCount: 38 },
  { id: 48, name: 'Al-Fath', arabic: 'الفتح', meaning: 'The Victory', ayahCount: 29 },
  { id: 49, name: 'Al-Hujurat', arabic: 'الحجرات', meaning: 'The Private Chambers', ayahCount: 18 },
  { id: 50, name: 'Qaf', arabic: 'ق', meaning: 'Qaf', ayahCount: 45 },
  { id: 51, name: 'Adh-Dhariyat', arabic: 'الذاريات', meaning: 'The Scatterers', ayahCount: 60 },
  { id: 52, name: 'At-Tur', arabic: 'الطور', meaning: 'The Mountain', ayahCount: 49 },
  { id: 53, name: 'An-Najm', arabic: 'النجم', meaning: 'The Star', ayahCount: 62 },
  { id: 54, name: 'Al-Qamar', arabic: 'القمر', meaning: 'The Moon', ayahCount: 55 },
  { id: 55, name: 'Ar-Rahman', arabic: 'الرحمن', meaning: 'The Beneficent', ayahCount: 78 },
  { id: 56, name: "Al-Waqi'ah", arabic: 'الواقعة', meaning: 'The Inevitable', ayahCount: 96 },
  { id: 57, name: 'Al-Hadid', arabic: 'الحديد', meaning: 'The Iron', ayahCount: 29 },
  { id: 58, name: 'Al-Mujadilah', arabic: 'المجادلة', meaning: 'The Pleading Woman', ayahCount: 22 },
  { id: 59, name: 'Al-Hashr', arabic: 'الحشر', meaning: 'The Exile', ayahCount: 24 },
  { id: 60, name: 'Al-Mumtahanah', arabic: 'الممتحنة', meaning: 'She That is to be Examined', ayahCount: 13 },
  { id: 61, name: 'As-Saff', arabic: 'الصف', meaning: 'The Ranks', ayahCount: 14 },
  { id: 62, name: "Al-Jumu'ah", arabic: 'الجمعة', meaning: 'Congregation Prayer', ayahCount: 11 },
  { id: 63, name: 'Al-Munafiqun', arabic: 'المنافقون', meaning: 'The Hypocrites', ayahCount: 11 },
  { id: 64, name: 'At-Taghabun', arabic: 'التغابن', meaning: 'Mutual Dispossession', ayahCount: 18 },
  { id: 65, name: 'At-Talaq', arabic: 'الطلاق', meaning: 'The Divorce', ayahCount: 12 },
  { id: 66, name: 'At-Tahrim', arabic: 'التحريم', meaning: 'The Prohibition', ayahCount: 12 },
  { id: 67, name: 'Al-Mulk', arabic: 'الملك', meaning: 'The Sovereignty', ayahCount: 30 },
  { id: 68, name: 'Al-Qalam', arabic: 'القلم', meaning: 'The Pen', ayahCount: 52 },
  { id: 69, name: "Al-Haqqah", arabic: 'الحاقة', meaning: 'The Reality', ayahCount: 52 },
  { id: 70, name: "Al-Ma'arij", arabic: 'المعارج', meaning: 'The Ascending Stairways', ayahCount: 44 },
  { id: 71, name: 'Nuh', arabic: 'نوح', meaning: 'Noah', ayahCount: 28 },
  { id: 72, name: 'Al-Jinn', arabic: 'الجن', meaning: 'The Jinn', ayahCount: 28 },
  { id: 73, name: 'Al-Muzzammil', arabic: 'المزمل', meaning: 'The Enshrouded One', ayahCount: 20 },
  { id: 74, name: 'Al-Muddaththir', arabic: 'المدثر', meaning: 'The Cloaked One', ayahCount: 56 },
  { id: 75, name: 'Al-Qiyamah', arabic: 'القيامة', meaning: 'The Resurrection', ayahCount: 40 },
  { id: 76, name: 'Al-Insan', arabic: 'الإنسان', meaning: 'The Man', ayahCount: 31 },
  { id: 77, name: 'Al-Mursalat', arabic: 'المرسلات', meaning: 'The Emissaries', ayahCount: 50 },
  { id: 78, name: "An-Naba'", arabic: 'النبأ', meaning: 'The Tidings', ayahCount: 40 },
  { id: 79, name: "An-Nazi'at", arabic: 'النازعات', meaning: 'Those Who Drag Forth', ayahCount: 46 },
  { id: 80, name: 'Abasa', arabic: 'عبس', meaning: 'He Frowned', ayahCount: 42 },
  { id: 81, name: 'At-Takwir', arabic: 'التكوير', meaning: 'The Overthrowing', ayahCount: 29 },
  { id: 82, name: 'Al-Infitar', arabic: 'الانفطار', meaning: 'The Cleaving', ayahCount: 19 },
  { id: 83, name: 'Al-Mutaffifin', arabic: 'المطففين', meaning: 'The Defrauding', ayahCount: 36 },
  { id: 84, name: 'Al-Inshiqaq', arabic: 'الانشقاق', meaning: 'The Sundering', ayahCount: 25 },
  { id: 85, name: 'Al-Buruj', arabic: 'البروج', meaning: 'The Mansions of the Stars', ayahCount: 22 },
  { id: 86, name: 'At-Tariq', arabic: 'الطارق', meaning: 'The Nightcomer', ayahCount: 17 },
  { id: 87, name: "Al-A'la", arabic: 'الأعلى', meaning: 'The Most High', ayahCount: 19 },
  { id: 88, name: 'Al-Ghashiyah', arabic: 'الغاشية', meaning: 'The Overwhelming', ayahCount: 26 },
  { id: 89, name: 'Al-Fajr', arabic: 'الفجر', meaning: 'The Dawn', ayahCount: 30 },
  { id: 90, name: 'Al-Balad', arabic: 'البلد', meaning: 'The City', ayahCount: 20 },
  { id: 91, name: 'Ash-Shams', arabic: 'الشمس', meaning: 'The Sun', ayahCount: 15 },
  { id: 92, name: 'Al-Layl', arabic: 'الليل', meaning: 'The Night', ayahCount: 21 },
  { id: 93, name: 'Ad-Duha', arabic: 'الضحى', meaning: 'The Morning Brightness', ayahCount: 11 },
  { id: 94, name: 'Ash-Sharh', arabic: 'الشرح', meaning: 'The Expansion', ayahCount: 8 },
  { id: 95, name: 'At-Tin', arabic: 'التين', meaning: 'The Fig', ayahCount: 8 },
  { id: 96, name: "Al-'Alaq", arabic: 'العلق', meaning: 'The Blood Clot', ayahCount: 19 },
  { id: 97, name: 'Al-Qadr', arabic: 'القدر', meaning: 'The Power', ayahCount: 5 },
  { id: 98, name: 'Al-Bayyinah', arabic: 'البينة', meaning: 'The Evidence', ayahCount: 8 },
  { id: 99, name: 'Az-Zalzalah', arabic: 'الزلزلة', meaning: 'The Earthquake', ayahCount: 8 },
  { id: 100, name: "Al-'Adiyat", arabic: 'العاديات', meaning: 'The Courser', ayahCount: 11 },
  { id: 101, name: "Al-Qari'ah", arabic: 'القارعة', meaning: 'The Calamity', ayahCount: 11 },
  { id: 102, name: 'At-Takathur', arabic: 'التكاثر', meaning: 'Vying for Increase', ayahCount: 8 },
  { id: 103, name: "Al-'Asr", arabic: 'العصر', meaning: 'The Declining Day', ayahCount: 3 },
  { id: 104, name: 'Al-Humazah', arabic: 'الهمزة', meaning: 'The Slanderer', ayahCount: 9 },
  { id: 105, name: 'Al-Fil', arabic: 'الفيل', meaning: 'The Elephant', ayahCount: 5 },
  { id: 106, name: 'Quraysh', arabic: 'قريش', meaning: 'Quraysh', ayahCount: 4 },
  { id: 107, name: "Al-Ma'un", arabic: 'الماعون', meaning: 'The Small Kindness', ayahCount: 7 },
  { id: 108, name: 'Al-Kawthar', arabic: 'الكوثر', meaning: 'The Abundance', ayahCount: 3 },
  { id: 109, name: 'Al-Kafirun', arabic: 'الكافرون', meaning: 'The Disbelievers', ayahCount: 6 },
  { id: 110, name: 'An-Nasr', arabic: 'النصر', meaning: 'The Divine Support', ayahCount: 3 },
  { id: 111, name: 'Al-Masad', arabic: 'المسد', meaning: 'The Palm Fiber', ayahCount: 5 },
  { id: 112, name: 'Al-Ikhlas', arabic: 'الإخلاص', meaning: 'The Sincerity', ayahCount: 4 },
  { id: 113, name: 'Al-Falaq', arabic: 'الفلق', meaning: 'The Daybreak', ayahCount: 5 },
  { id: 114, name: 'An-Nas', arabic: 'الناس', meaning: 'The Mankind', ayahCount: 6 },
];

// Key ayahs for each surah (first few + famous ones). 
// For full surah, we generate placeholders using real translations for short surahs.
/* eslint-disable */
// @deprecated — SurahDetail now fetches real ayahs from api.alquran.cloud at runtime.
export const SURAH_AYAHS = {
  1: [
    { n: 1, ar: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ', en: 'In the name of Allah, the Entirely Merciful, the Especially Merciful.' },
    { n: 2, ar: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ', en: 'All praise is due to Allah, Lord of the worlds.' },
    { n: 3, ar: 'الرَّحْمَٰنِ الرَّحِيمِ', en: 'The Entirely Merciful, the Especially Merciful.' },
    { n: 4, ar: 'مَالِكِ يَوْمِ الدِّينِ', en: 'Sovereign of the Day of Recompense.' },
    { n: 5, ar: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ', en: 'It is You we worship and You we ask for help.' },
    { n: 6, ar: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ', en: 'Guide us to the straight path —' },
    { n: 7, ar: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ', en: 'The path of those upon whom You have bestowed favor, not of those who have evoked anger or of those who are astray.' },
  ],
  94: [
    { n: 1, ar: 'أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ', en: 'Did We not expand for you your breast [O Muhammad]?' },
    { n: 2, ar: 'وَوَضَعْنَا عَنكَ وِزْرَكَ', en: 'And We removed from you your burden' },
    { n: 3, ar: 'الَّذِي أَنقَضَ ظَهْرَكَ', en: 'Which had weighed upon your back' },
    { n: 4, ar: 'وَرَفَعْنَا لَكَ ذِكْرَكَ', en: 'And raised high for you your repute.' },
    { n: 5, ar: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا', en: 'For indeed, with hardship will be ease.' },
    { n: 6, ar: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا', en: 'Indeed, with hardship will be ease.' },
    { n: 7, ar: 'فَإِذَا فَرَغْتَ فَانصَبْ', en: 'So when you have finished [your duties], then stand up [for worship].' },
    { n: 8, ar: 'وَإِلَىٰ رَبِّكَ فَارْغَب', en: 'And to your Lord direct [your] longing.' },
  ],
  112: [
    { n: 1, ar: 'قُلْ هُوَ اللَّهُ أَحَدٌ', en: 'Say: He is Allah, the One.' },
    { n: 2, ar: 'اللَّهُ الصَّمَدُ', en: 'Allah, the Eternal Refuge.' },
    { n: 3, ar: 'لَمْ يَلِدْ وَلَمْ يُولَدْ', en: 'He neither begets nor is born.' },
    { n: 4, ar: 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ', en: 'Nor is there to Him any equivalent.' },
  ],
  113: [
    { n: 1, ar: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ', en: 'Say: I seek refuge in the Lord of daybreak.' },
    { n: 2, ar: 'مِن شَرِّ مَا خَلَقَ', en: 'From the evil of that which He created.' },
    { n: 3, ar: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ', en: 'And from the evil of darkness when it settles.' },
    { n: 4, ar: 'وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ', en: 'And from the evil of the blowers in knots.' },
    { n: 5, ar: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ', en: 'And from the evil of an envier when he envies.' },
  ],
  114: [
    { n: 1, ar: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ', en: 'Say: I seek refuge in the Lord of mankind.' },
    { n: 2, ar: 'مَلِكِ النَّاسِ', en: 'The Sovereign of mankind.' },
    { n: 3, ar: 'إِلَٰهِ النَّاسِ', en: 'The God of mankind.' },
    { n: 4, ar: 'مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ', en: 'From the evil of the retreating whisperer.' },
    { n: 5, ar: 'الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ', en: 'Who whispers in the breasts of mankind.' },
    { n: 6, ar: 'مِنَ الْجِنَّةِ وَالنَّاسِ', en: 'From among the jinn and mankind.' },
  ],
  103: [
    { n: 1, ar: 'وَالْعَصْرِ', en: 'By time,' },
    { n: 2, ar: 'إِنَّ الْإِنسَانَ لَفِي خُسْرٍ', en: 'Indeed, mankind is in loss,' },
    { n: 3, ar: 'إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ', en: 'Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.' },
  ],
  108: [
    { n: 1, ar: 'إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ', en: 'Indeed, We have granted you Al-Kawthar.' },
    { n: 2, ar: 'فَصَلِّ لِرَبِّكَ وَانْحَرْ', en: 'So pray to your Lord and sacrifice [to Him alone].' },
    { n: 3, ar: 'إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ', en: 'Indeed, your enemy is the one cut off.' },
  ],
  110: [
    { n: 1, ar: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ', en: 'When the victory of Allah has come and the conquest,' },
    { n: 2, ar: 'وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا', en: 'And you see the people entering into the religion of Allah in multitudes,' },
    { n: 3, ar: 'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا', en: 'Then exalt [Him] with praise of your Lord and ask forgiveness of Him. Indeed, He is ever Accepting of repentance.' },
  ],
};

// Generate placeholder ayahs for surahs without full data
export function getAyahsForSurah(surahId) {
  if (SURAH_AYAHS[surahId]) return SURAH_AYAHS[surahId];
  const surah = SURAHS.find(s => s.id === surahId);
  if (!surah) return [];
  // Generate numbered ayahs with bismillah placeholder
  return Array.from({ length: surah.ayahCount }, (_, i) => ({
    n: i + 1,
    ar: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
    en: `[${surah.name} ${surahId}:${i + 1}] — Tap "Mark as Read" to earn +2 BP for this ayah.`,
  }));
}